---
name: Submit Dependencies

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v3
